### ISSUE TITLE
Collab on shared lower-level concurrency lib?

### ISSUE THREAD

**Issue by machty** [encyjs/vuency#19]
Since releasing ember-concurrency, a lot of people have been asking me if/how/when they could use tasks for, say, node.js server development and other use cases. I've started to think about how to extract portions of e-c to a non-Ember-dependent library, and it'd be nice if the other various concurrency libs targeting specific UI libs (like vuency, perhaps react-concurrency) could share the same underlying primitives.

We talked about this briefly on Twitter but I figured I'd open an issue here early to get the ball rolling before we both write the same thing twice.

**Comment by alidcastano** [comment]
Interesting, I didn't know `react-concurrency` existed. 

I agree that we should work together to solve the same problem. (Kind of like [`mobiledoc-kit`](https://github.com/bustlelabs/mobiledoc-kit), which you're probably familiar with, provides a core library that can be implemented in other frameworks like Ember, React, and Vue.)

I was even asked on the [Vue forum](https://forum.vuejs.org/t/the-first-concurrency-management-plugin-for-vuejs/9025) why this was closely tied to Vue. And it doesn't have to be. 95% of Vuency is just JS, only the mixin application and wrapper functions for `watchers` and `events` are tied to Vue. The only reason I stuck with Vue was that I thought that it would be helpful to create the project within a niche, as I could easily extract the useful parts later if it was found useful. But I'd definitely be interested in working together, taken the best of our implementations, and doing it earlier.

I'm curious, what do you define as a task primitive? 

I previously looked at what general javascript implementations existed for tasks. I was actually surprised not to find much. The only thing that I could find about tasks was [taskjs](https://github.com/mozilla/task.js). But the project is pretty outdated and doesn't seem to have been taken anywhere.
